import type { AmortizationRow } from './formulas';

/**
 * Export amortization schedule as CSV file.
 * Compatible with Excel, Google Sheets, OpenOffice.
 */
export function exportAmortizationCSV(
    rows: AmortizationRow[],
    filename = 'USFinNexus-Amortization-Schedule.csv'
): void {
    const headers = [
        'Month', 'Date', 'Payment', 'Principal', 'Interest',
        'Extra Payment', 'Balance', 'Cumulative Interest', 'Cumulative Principal',
    ];

    const csvRows = [
        headers.join(','),
        `# Generated by USFinNexus.com | ${new Date().toLocaleDateString('en-US')} | For estimation purposes only`,
        ...rows.map(r => [
            r.month,
            r.date.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' }),
            r.payment.toFixed(2),
            r.principal.toFixed(2),
            r.interest.toFixed(2),
            r.extraPayment.toFixed(2),
            r.balance.toFixed(2),
            r.cumulativeInterest.toFixed(2),
            r.cumulativePrincipal.toFixed(2),
        ].join(',')),
    ];

    downloadCSV(csvRows.join('\n'), filename);
}

/**
 * Export a generic data table as CSV.
 */
export function exportGenericCSV(
    headers: string[],
    rows: (string | number)[][],
    filename = 'USFinNexus-Export.csv'
): void {
    const csvRows = [
        headers.join(','),
        `# Generated by USFinNexus.com | ${new Date().toLocaleDateString('en-US')}`,
        ...rows.map(r => r.map(cell =>
            typeof cell === 'string' && cell.includes(',') ? `"${cell}"` : String(cell)
        ).join(',')),
    ];
    downloadCSV(csvRows.join('\n'), filename);
}

function downloadCSV(content: string, filename: string): void {
    const BOM = '\uFEFF'; // UTF-8 BOM for Excel compatibility
    const blob = new Blob([BOM + content], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
