import React from 'react';

export default function ArmSeoContent() {
    return (
        <section className="bg-white border-t border-gray-100 py-16 mt-8">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-lg prose-blue">
                <h2 className="text-3xl font-black text-navy-900 mb-6">
                    Fixed-Rate vs. Adjustable-Rate Mortgage (ARM)
                </h2>
                <p className="lead text-xl text-gray-600">
                    When mortgage rates are high, Adjustable-Rate Mortgages (ARMs) surge in popularity because they offer a &quot;teaser&quot; rate that is significantly lower than a standard 30-year fixed loan. However, an ARM transfers the interest rate risk from the bank directly onto you.
                </p>

                <h3 className="text-2xl font-bold mt-10 mb-4 text-navy-800">
                    How Does an ARM Work?
                </h3>
                <p>
                    An ARM is typically formatted with two numbers, such as a <strong>5/1 ARM</strong> or a <strong>7/1 ARM</strong>.
                </p>
                <ul>
                    <li><strong>The First Number (5):</strong> This is the length of the introductory &quot;fixed&quot; period. For the first 5 years, your low interest rate is locked and guaranteed not to change.</li>
                    <li><strong>The Second Number (1):</strong> This indicates how often the rate can adjust after the initial period ends. A &quot;1&quot; means the rate will adjust once every year for the remaining 25 years of the loan. Some newer ARMs are structured as 5/6 (adjusting every 6 months).</li>
                </ul>
                
                <h3 className="text-2xl font-bold mt-10 mb-4 text-navy-800">
                    Understanding the &quot;Worst-Case Scenario&quot; Caps
                </h3>
                <p>
                    By law, lenders must protect borrowers from infinite rate hikes. They do this through three specific rate caps (e.g., 2/1/5 or 2/2/5).
                </p>
                <div className="bg-blue-50 p-6 rounded-xl border border-blue-100 my-6">
                    <ul className="mb-0">
                        <li><strong>Initial Cap (e.g., 2%):</strong> The maximum amount the rate can increase on the very first adjustment (Month 61).</li>
                        <li><strong>Periodic Cap (e.g., 1%):</strong> The maximum amount the rate can increase on any subsequent yearly adjustment.</li>
                        <li><strong>Lifetime Cap (e.g., 5%):</strong> The absolute maximum your rate can ever increase above your initial teaser rate. If you start at 5%, your rate can never legally exceed 10%.</li>
                    </ul>
                </div>
                <p>
                    <strong>The Golden Rule of ARMs:</strong> Before signing an ARM, you must calculate the exact monthly payment if the rate hits its Lifetime Cap. If you cannot afford that &quot;Worst-Case&quot; payment, you should not take the loan. Our calculator perfectly simulates this worst-case scenario.
                </p>

                <h3 className="text-2xl font-bold mt-10 mb-4 text-navy-800">
                    When is an ARM a Good Idea?
                </h3>
                <p>
                    Despite the risks, an ARM can be a brilliant financial maneuver in specific situations:
                </p>
                <ul>
                    <li><strong>Short-Term Ownership:</strong> If you are absolutely certain you will sell the home or move within 5 to 7 years (e.g., military orders, a residency program). You get the ultra-low rate for the entire time you live there, and sell the house before the rate ever has a chance to adjust.</li>
                    <li><strong>Planned Refinance:</strong> You take the ARM to get the lowest payment today, with the aggressive plan to refinance into a 30-year fixed loan within the next few years when broader market rates drop. (Always remember: refinancing is never guaranteed if your credit drops or home values fall).</li>
                    <li><strong>Aggressive Paydown:</strong> You use the monthly cash flow savings generated by the low ARM rate to aggressively pay down the principal balance. By the time the rate adjusts upward, your loan balance is so small that the payment remains affordable.</li>
                </ul>
            </div>
        </section>
    );
}
