import type { Metadata } from 'next';
import Link from 'next/link';
import ContextualInternalLinks from '@/components/ContextualInternalLinks';
import Breadcrumbs from '@/components/Breadcrumbs';
import CalculatorFAQ from '@/components/CalculatorFAQ';
import WebApplicationSchema from '@/components/WebApplicationSchema';
import TemporaryBuydownClient from './TemporaryBuydownClient';
const url='https://usfinnexus.com/calculators/temporary-buydown';
export const dynamic='force-static'; export const revalidate=86400;
export const metadata: Metadata={title:'2-1 Buydown Calculator 2026: Temporary Rate Payment Savings',description:'Model 1-0, 2-1, and 3-2-1 temporary buydowns. See year-by-year payments and the seller or builder subsidy needed. Free, no email.',alternates:{canonical:url},openGraph:{type:'website',title:'2-1 Buydown Calculator 2026',description:'Compare temporary buydown payments with the full note rate.',url,siteName:'USFinNexus'},twitter:{card:'summary_large_image',title:'2-1 Buydown Calculator 2026',description:'Model 1-0, 2-1 and 3-2-1 temporary mortgage buydowns.'}};
const faqs=[{question:'What is a 2-1 buydown?',answer:'A 2-1 buydown temporarily reduces the note rate by two percentage points in year one and one point in year two, then returns to the full note rate.'},{question:'Who pays for a temporary buydown?',answer:'A seller, builder or other permitted party often funds the subsidy at closing, subject to the loan program and applicable contribution limits.'},{question:'Do I qualify at the lower buydown rate?',answer:'Usually underwriting uses the full note rate or program-specific qualifying payment, not the temporary teaser payment. Confirm with the lender.'},{question:'2-1 buydown vs buying points?',answer:'A temporary buydown subsidizes early payments; discount points permanently reduce the note rate. Compare cash cost, break-even timing and how long you expect to keep the loan.'},{question:'What happens to unused funds if I refinance?',answer:'The agreement and servicer rules control. Ask for written treatment of any remaining subsidy before assuming it becomes cash to you.'}];
export default function TemporaryBuydownPage(){return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><WebApplicationSchema name="Temporary Buydown Calculator 2026" description="Compare 1-0, 2-1 and 3-2-1 temporary mortgage buydowns." url={url} dateModified="2026-09-12"/><Breadcrumbs items={[{name:'Calculators',item:'/calculators'},{name:'Temporary Buydown Calculator',item:'/calculators/temporary-buydown'}]}/><header className="mx-auto mb-8 max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.2em] text-blue-700">Reviewed September 12, 2026 · Educational estimate</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">Temporary Buydown Calculator (2-1, 3-2-1 &amp; 1-0)</h1><p className="mt-4 text-xl leading-relaxed text-slate-600"><strong>Quick answer:</strong> A temporary buydown lowers the payment for early years while the loan keeps its full note rate. Model the subsidy and the payment you must qualify for.</p></header><TemporaryBuydownClient/><article className="prose prose-slate mx-auto mt-10 max-w-3xl"><h2>Temporary vs. permanent rate buydowns</h2><p>This calculator models temporary payment subsidies. A permanent discount-point purchase works differently; compare it in the <Link href="/calculators/points-buydown">Points Buy-Down Calculator</Link>.</p><h2>How much must the seller or builder fund?</h2><p>The estimated subsidy is the difference between the full-note payment and each temporary payment, multiplied by the number of months. Actual agreements can include taxes, insurance, escrow and program-specific rules.</p><h2>Use the full payment for affordability</h2><p>Compare the note-rate payment with the <Link href="/calculators/mortgage">Mortgage Calculator</Link>, <Link href="/calculators/affordability">Affordability Calculator</Link> and <Link href="/calculators/closing-costs">Closing Cost Calculator</Link>.</p><p className="not-prose rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Results are illustrative, exclude taxes, insurance and PMI, and are not a lender quote or approval decision.</p></article><CalculatorFAQ faqs={faqs} title="Temporary Buydown FAQs"/><ContextualInternalLinks currentSlug="temporary-buydown" showBlogs showCalculators/></main>}
