import type { Metadata } from 'next';
import Link from 'next/link';
import Breadcrumbs from '@/components/Breadcrumbs';
import WebApplicationSchema from '@/components/WebApplicationSchema';
import CalculatorFAQ from '@/components/CalculatorFAQ';
import ContextualInternalLinks from '@/components/ContextualInternalLinks';
import AffordabilityClient from '../AffordabilityClient';
export const dynamic='force-static'; export const revalidate=86400;
export function generateStaticParams(){return [60000,75000,100000,120000,150000,200000].map(s=>({salary:String(s)}));}
export async function generateMetadata({params}:{params:Promise<{salary:string}>}):Promise<Metadata>{const {salary}=await params;const n=Number(salary).toLocaleString();const u=`https://usfinnexus.com/calculators/affordability/salary-${salary}`;return {title:`How Much House Can I Afford on $${n}? 2026 Calculator`,description:`Estimate a 2026 home-price range on a $${n} salary using income, debts, rate and down payment. Free affordability calculator—no signup.`,alternates:{canonical:u},openGraph:{type:'website',title:`How Much House Can I Afford on $${n}?`,description:`Model home affordability on a $${n} annual salary.`,url:u,siteName:'USFinNexus'}}}
const faqs=(n:string)=>[{question:`How much house can I afford on $${n} in 2026?`,answer:`It depends on debts, down payment, rate, taxes, insurance and reserves. Use this page as a planning scenario, then customize the inputs in the calculator.`},{question:'Is the salary figure before or after taxes?',answer:'The calculator uses gross monthly income before taxes for DTI-style planning. Your comfortable budget should also consider take-home pay and non-debt expenses.'},{question:'How much income do I need for a larger house?',answer:'Use the main affordability calculator to reverse the scenario with your target payment, debts, rate and down payment.'}];
export default async function SalaryPage({params}:{params:Promise<{salary:string}>}){const {salary}=await params;const amount=Number(salary);const n=amount.toLocaleString();const url=`https://usfinnexus.com/calculators/affordability/salary-${salary}`;return <main className="mx-auto max-w-7xl px-4 py-8"><WebApplicationSchema name={`How Much House Can I Afford on $${n}?`} description={`Salary-based affordability planning for a $${n} annual income.`} url={url} dateModified="2026-09-12"/><Breadcrumbs items={[{name:'Calculators',item:'/calculators'},{name:'Affordability by Salary',item:'/calculators/affordability/by-salary'},{name:`$${n} Salary`,item:`/calculators/affordability/salary-${salary}`}]} /><header className="mx-auto mb-8 max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.2em] text-blue-700">Reviewed September 12, 2026 · Gross-income planning scenario</p><h1 className="mt-3 text-4xl font-black">How Much House Can I Afford on ${n}?</h1><p className="mt-4 text-xl text-slate-600"><strong>Quick answer:</strong> A ${n} salary is only one input. Debts, rate, down payment, property tax, insurance and reserves can materially change the range. Enter your actual assumptions below.</p></header><AffordabilityClient initialMonthlyIncome={amount/12}/><article className="prose prose-slate mx-auto mt-10 max-w-3xl"><h2>What this ${n} salary scenario means</h2><p>This page starts with a gross-income planning concept. The interactive calculator lets you adjust debts, down payment, rate, term and property-tax assumptions. Its 28% and 43% outputs are scenarios—not universal approval limits.</p><h2>Use rate and down payment tables carefully</h2><p>At a higher rate, the same payment supports a smaller loan. A larger down payment can reduce the amount financed, but do not empty emergency savings to reach a percentage target. Compare the resulting payment in the <Link href="/calculators/mortgage">Mortgage Calculator</Link> and check your obligations in the <Link href="/calculators/dti">DTI Calculator</Link>.</p><h2>Approval is not affordability</h2><p>A lender evaluates program rules, credit, assets and documentation. Your household budget should also include maintenance, utilities, childcare, health costs and irregular expenses.</p></article><CalculatorFAQ faqs={faqs(n)} title="Salary Affordability FAQs"/><ContextualInternalLinks currentSlug={`affordability-salary-${salary}`} showBlogs showCalculators/></main>}
