import type { Metadata } from 'next';
import Link from 'next/link';
import AuthorBio, { USFinNexusEditorialTeam } from '@/components/AuthorBio';
import RelatedCalculators from '@/components/RelatedCalculators';
import Breadcrumbs from '@/components/Breadcrumbs';
import ArticleSchema from '@/components/ArticleSchema';
export const metadata: Metadata = { title: 'Closing Costs: How Much You'll Actually Pay (Itemized) - USFinNexus', description: 'Closing costs include appraisals, inspections, title, and more. See a full itemized breakdown.', openGraph: { title: 'Closing Costs: How Much You'll Actually Pay (Itemized)', description: 'Closing costs include appraisals, inspections, title, and more. See a full itemized breakdown.', url: 'https://usfinnexus.com/blog/closing-costs-itemized-breakdown-2026', type: 'article', siteName: 'USFinNexus' }, alternates: { canonical: 'https://usfinnexus.com/blog/closing-costs-itemized-breakdown-2026' } };
export default function PostComponent() {
    return (<><ArticleSchema title="Closing Costs: How Much You'll Actually Pay (Itemized)" description="Closing costs include appraisals, inspections, title, and more. See a full itemized breakdown." url="https://usfinnexus.com/blog/closing-costs-itemized-breakdown-2026" datePublished="2026-05-15" dateModified="2026-05-15" authorName="USFinNexus Editorial Team" keywords={['finance']} /><div className="max-w-4xl mx-auto px-4 py-7"><Breadcrumbs items={[{ name: 'Blog', item: '/blog' }, { name: 'Closing Costs: How Much You'll Actually Pay (Itemized)', item: '/blog/closing-costs-itemized-breakdown-2026' }]} /><article className="prose prose-slate max-w-none"><header className="mb-10"><h1 className="text-4xl font-black mb-6">Closing Costs: How Much You'll Actually Pay (Itemized)</h1></header><div className="prose-lg"><p className="text-xl mb-8">Closing costs include appraisals, inspections, title, and more. See a full itemized breakdown.</p><h2 className="text-2xl font-bold mt-12 mb-4">Learn More</h2><p>Use <Link href="https://usfinnexus.com" className="text-blue-600">calculators</Link> to explore scenarios.</p></div></article><div className="mt-12"><RelatedCalculators calculators={['mortgage']} /><AuthorBio author={USFinNexusEditorialTeam} /></div></div></> );
}
