import type { Metadata } from 'next';
import Link from 'next/link';
import AuthorBio, { USFinNexusEditorialTeam } from '@/components/AuthorBio';
import RelatedCalculators from '@/components/RelatedCalculators';
import Breadcrumbs from '@/components/Breadcrumbs';
import ArticleSchema from '@/components/ArticleSchema';

export const metadata: Metadata = { title: 'The 28/36 Rule Explained: How Lenders Size Your Mortgage - USFinNexus 2026', description: 'The 28/36 rule is the lender standard for mortgage affordability. Learn how it works and what it means for you.', openGraph: { title: 'The 28/36 Rule Explained: How Lenders Size Your Mortgage', description: 'The 28/36 rule is the lender standard for mortgage affordability. Learn how it works and what it means for you.', url: 'https://usfinnexus.com/blog/28-36-rule-explained-lender-standards', type: 'article', siteName: 'USFinNexus' }, alternates: { canonical: 'https://usfinnexus.com/blog/28-36-rule-explained-lender-standards' } };

export default function PostComponent() {
    return (<><ArticleSchema title="The 28/36 Rule Explained: How Lenders Size Your Mortgage" description="The 28/36 rule is the lender standard for mortgage affordability. Learn how it works and what it means for you." url="https://usfinnexus.com/blog/28-36-rule-explained-lender-standards" datePublished="2026-05-15" dateModified="2026-05-15" authorName="USFinNexus Editorial Team" keywords={['finance']} /><div className="max-w-4xl mx-auto px-4 py-7 sm:py-9"><Breadcrumbs items={[{ name: 'Blog', item: '/blog' }, { name: 'The 28/36 Rule Explained: How Lenders Size Your Mortgage', item: '/blog/28-36-rule-explained-lender-standards' }]} /><article className="prose prose-slate max-w-none"><header className="mb-10"><h1 className="text-4xl font-black mb-6">The 28/36 Rule Explained: How Lenders Size Your Mortgage</h1><div className="text-sm text-gray-600"><span>By {USFinNexusEditorialTeam.name}</span><span> · May 2026</span></div></header><div className="prose-lg"><p className="text-xl mb-8">The 28/36 rule is the lender standard for mortgage affordability. Learn how it works and what it means for you.</p><h2 className="text-2xl font-bold mt-12 mb-4">Key Details</h2><p>Learn the fundamentals and use <Link href="https://usfinnexus.com" className="text-blue-600">calculators</Link> to model your situation.</p><h2 className="text-2xl font-bold mt-12 mb-4">Get Started</h2><div className="bg-blue-50 p-6 mb-8 border-l-4 border-blue-500"><p>Use our free tools to test scenarios and make informed decisions.</p></div></div></article><div className="mt-12"><RelatedCalculators calculators={['mortgage']} /><AuthorBio author={USFinNexusEditorialTeam} /></div></div></> );
}
