import type { Metadata } from 'next';
import Link from 'next/link';
import ArticleSchema from '@/components/ArticleSchema';
import Breadcrumbs from '@/components/Breadcrumbs';
import CalculatorFAQ from '@/components/CalculatorFAQ';

const url='https://usfinnexus.com/blog/tax-loss-harvesting-wash-sale-2026';
const image='https://usfinnexus.com/images/tax-loss-harvesting-wash-sale-2026.svg';
const faqs=[{"question":"Can I sell a stock at a loss and buy it back the next day?","answer":"The IRS wash-sale rule generally disallows the loss when substantially identical stock or securities are acquired within 30 days before or after the sale."},{"question":"Does the wash-sale rule erase the loss?","answer":"Usually the disallowed loss is added to the basis of the replacement position, deferring the tax benefit rather than eliminating it."},{"question":"Do purchases in my spouse’s account matter?","answer":"They can. Review the IRS rules across taxable, IRA and spouse accounts before harvesting."},{"question":"Can I harvest losses in an IRA?","answer":"An IRA purchase can create wash-sale complications, and the basis adjustment may not work like a taxable-account replacement. Get professional advice."},{"question":"Does wash-sale treatment apply to every cryptocurrency?","answer":"Not necessarily. Digital-asset reporting and the stock-or-securities rule require careful facts and current guidance."},{"question":"Is tax-loss harvesting always worth doing?","answer":"No. Taxes are one input. Trading costs, allocation, risk and time out of the market also matter."}];
export const metadata:Metadata={
 title:'Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End',
 description:'Learn how tax-loss harvesting works in 2026, the IRS 30-day wash-sale rule, replacement investments, digital assets and recordkeeping.',
 alternates:{canonical:url},
 openGraph:{type:'article',title:'Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End',description:'Learn how tax-loss harvesting works in 2026, the IRS 30-day wash-sale rule, replacement investments, digital assets and recordkeeping.',url,siteName:'USFinNexus',images:[{url:image,width:1200,height:630,alt:'Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End editorial hero graphic'}]},
 twitter:{card:'summary_large_image',title:'Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End',description:'Learn how tax-loss harvesting works in 2026, the IRS 30-day wash-sale rule, replacement investments, digital assets and recordkeeping.',images:[image]}
};
export default function Page(){
 return <><ArticleSchema title="Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End" description="Learn how tax-loss harvesting works in 2026, the IRS 30-day wash-sale rule, replacement investments, digital assets and recordkeeping." url={url} datePublished="2026-10-06" dateModified="2026-10-06" authorName="USFinNexus Editorial Team" image={image} keywords={["tax-loss harvesting 2026","wash sale rule 2026","sell stock at a loss tax"]}/>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map((f:any)=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))})}}/>
 <main className="max-w-4xl mx-auto px-4 py-8"><Breadcrumbs items={[{name:'Blog',item:'/blog'},{name:'Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End',item:'/blog/tax-loss-harvesting-wash-sale-2026'}]}/><article className="prose prose-slate max-w-none">
 <p className="text-sm font-bold uppercase tracking-wider text-blue-700">Investing & Taxes · Reviewed October 6, 2026</p>
 <h1>Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End</h1>
 <p className="lead"><strong>Answer first:</strong> Tax-loss harvesting means selling an investment below its tax basis to realize a capital loss that can offset capital gains. The strategy is legal, but the IRS wash-sale rule can defer the loss when you buy substantially identical stock or securities within 30 days before or after the sale. A sale alone does not guarantee a deduction.</p>
 <div className="not-prose my-8 overflow-hidden rounded-2xl border border-slate-200 bg-slate-950"><img src="/images/tax-loss-harvesting-wash-sale-2026.svg" alt="Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End editorial hero graphic" width="1200" height="630" className="h-auto w-full" /></div>
 <aside className="not-prose my-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950">Educational information only. This article is not tax, Medicare, legal, mortgage, insurance or investment advice. Confirm current rules with the official source and a qualified professional before acting.</aside>
 <h2>What a harvested loss can do</h2><p>Capital losses first offset capital gains under the federal rules. If losses exceed gains, an individual may generally deduct a limited amount against other income and carry unused losses forward, subject to the applicable return rules. Your brokerage statement may show proceeds and basis, but you remain responsible for complete reporting.</p><h2>The 30-day wash-sale window</h2><p>A wash sale can arise when you sell at a loss and acquire substantially identical stock or securities within 30 days before or after the sale. The rule can also involve a spouse’s purchase, an IRA or another account. The disallowed loss is generally added to the replacement position’s basis rather than disappearing forever, which changes when the tax benefit becomes available.</p><h2>How to choose a replacement</h2><p>Investors often replace a broad fund with a different fund that has similar exposure but is not substantially identical. The IRS does not provide a simple ticker-by-ticker safe list. Compare holdings, index methodology and fund structure, and document why the replacement is different. Do not let a tax trade create an unintended portfolio concentration.</p><h2>Year-end timing and settlement</h2><p>The sale must occur in the tax year you want to recognize, and market holidays, settlement conventions and broker cutoffs can create operational risk. Review unrealized gains and losses before December, then leave enough time to confirm the trade, basis and any replacement purchase. Do not wait for the final trading session.</p><h2>Digital assets and special records</h2><p>The IRS treats digital assets under separate reporting guidance, and the wash-sale analysis can differ because the statutory stock-or-securities rule may not apply in the same way to every token. Keep wallet, exchange and transfer records. Do not assume that a crypto loss follows the same answer as a stock loss.</p><h2>A disciplined checklist</h2><p>Export lot-level records, identify realized gains, check all accounts for purchases, decide whether the replacement still fits your allocation and save the tax-lot decision. Use the investment calculator for scenarios, then verify the final Form 8949 and Schedule D reporting with current IRS instructions or a tax professional.</p>
 <h2>A safer year-end harvesting workflow</h2><p>Begin with a complete lot report from every taxable brokerage account. A single fund can have dozens of lots with different basis and holding periods. Separate long-term and short-term results, then compare realized gains with losses already reported. Do not rely only on the unrealized gain column because reinvested dividends, transfers and corporate actions can change basis.</p><p>Before selling, search for purchases in the previous 30 days and planned automatic reinvestments in the next 30 days. Turn off dividend reinvestment temporarily if it could create a replacement share. Check a spouse’s account and IRAs as well. Your broker may not see every related-account transaction, so a clean 1099-B does not prove that the wash-sale rule was avoided.</p><p>Decide the replacement investment before submitting the sale. It should preserve the portfolio exposure you need without being substantially identical under the facts. Document the reason for the replacement, the trade date and the new basis. If the market moves sharply, a tax benefit is not worth abandoning a long-term allocation or buying an asset you would not hold without the deduction.</p><ul><li>Export lot-level statements.</li><li>Check automatic dividend purchases.</li><li>Review spouse and IRA activity.</li><li>Leave time for year-end settlement.</li><li>Store Form 8949 support records.</li></ul>
<h2>Useful USFinNexus tools</h2><p><Link href="/calculators/investment">investment calculator</Link> · <Link href="/calculators/income-tax">income-tax calculator</Link> · <Link href="/blog/capital-gains-tax-rates-2026">2026 capital-gains guide</Link>.</p>
 <h2>Official source</h2><p><a href="https://www.irs.gov/publications/p550" target="_blank" rel="noopener noreferrer">IRS Publication 550, Investment Income and Expenses</a>. Always check the latest publication, plan document or notice because rules and costs can change.</p>
 <h2>Frequently asked questions</h2><CalculatorFAQ faqs={faqs} title="Tax-Loss Harvesting 2026: Wash-Sale Rules Before Year-End FAQs"/>
 <h2>Disclaimer</h2><p>Figures and rules are presented for general education and were checked on October 6, 2026. Your eligibility, filing status, plan, lender, state and account documents control. Do not make a financial decision solely from this article.</p>
 </article></main></>;
}
