import type { Metadata } from 'next';
import Link from 'next/link';
import AuthorBio, { USFinNexusEditorialTeam } from '@/components/AuthorBio';
import RelatedCalculators from '@/components/RelatedCalculators';
import Breadcrumbs from '@/components/Breadcrumbs';
import ArticleSchema from '@/components/ArticleSchema';
export const metadata: Metadata = { title: 'Appraisal Contingency: What Happens if Your Home Appraises Low - USFinNexus', description: 'A low appraisal can derail a deal. Understand contingencies and your options.', openGraph: { title: 'Appraisal Contingency: What Happens if Your Home Appraises Low', description: 'A low appraisal can derail a deal. Understand contingencies and your options.', url: 'https://usfinnexus.com/blog/appraisal-contingency-low-appraisal', type: 'article', siteName: 'USFinNexus' }, alternates: { canonical: 'https://usfinnexus.com/blog/appraisal-contingency-low-appraisal' } };
export default function PostComponent() {
    return (<><ArticleSchema title="Appraisal Contingency: What Happens if Your Home Appraises Low" description="A low appraisal can derail a deal. Understand contingencies and your options." url="https://usfinnexus.com/blog/appraisal-contingency-low-appraisal" datePublished="2026-05-15" dateModified="2026-05-15" authorName="USFinNexus Editorial Team" keywords={['finance']} /><div className="max-w-4xl mx-auto px-4 py-7"><Breadcrumbs items={[{ name: 'Blog', item: '/blog' }, { name: 'Appraisal Contingency: What Happens if Your Home Appraises Low', item: '/blog/appraisal-contingency-low-appraisal' }]} /><article className="prose prose-slate max-w-none"><header className="mb-10"><h1 className="text-4xl font-black mb-6">Appraisal Contingency: What Happens if Your Home Appraises Low</h1></header><div className="prose-lg"><p className="text-xl mb-8">A low appraisal can derail a deal. Understand contingencies and your options.</p><h2 className="text-2xl font-bold mt-12 mb-4">Learn More</h2><p>Use <Link href="https://usfinnexus.com" className="text-blue-600">calculators</Link> to explore scenarios.</p></div></article><div className="mt-12"><RelatedCalculators /><AuthorBio author={USFinNexusEditorialTeam} /></div></div></> );
}
